resolver: lts-5.11

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

packages:
- '.'
- location:
    git: https://github.com/ghcjs/ghcjs-base.git
    commit: e9e9e36afde694202de034905efdeef153e1b04d
  extra-dep: true
- location:
    git: https://github.com/ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
  extra-dep: true
- location:
    git: https://github.com/meteogrid/sigym4-geometry.git
    commit: a64f3dbeadb0285fe65ca8fd54a71e6e5486345e
  extra-dep: true
- location:
    git: https://github.com/meteogrid/spatial-reference.git
    commit: f4deaea7abe752105275abfc61338e0d9cfe7522
  extra-dep: true

extra-deps:
  - these-0.6.2.0
  - string-conv-0.1
  - ghcjs-dom-0.2.3.1
  - haskell-src-exts-1.16.0.1
  - reflex-0.4.0
  - reflex-dom-0.3
  - reflex-dom-contrib-0.4.1
  - ref-tf-0.4

flags: {}
extra-package-dbs: []
