resolver: lts-3.19
compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151029_ghc-7.10.2:
        url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"

packages:
- '.'
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: a60ae687cdc284a8eb3776fc95aa2adefc51e7ec # hamishmack-master (improved-base compatible)
  extra-dep: true
- location:
    git: https://github.com/ghcjs/ghcjs-base.git
    commit: 68bd5761e6a555d8a6780512215d9993dc6f2d82
  extra-dep: true

extra-deps:
  - ghcjs-dom-0.2.3.0
  - reflex-0.3.2
  - ref-tf-0.4
  - these-0.6.2.0

flags: {}
extra-package-dbs: []
